runtime: python38

instance_class: F1

env_variables:
  MYSQL_USER: 'root'
  MYSQL_PASSWORD: 'cs411'
  MYSQL_DB: 'vaccine_tracker'
  MYSQL_HOST: '34.122.181.200'

handlers:
- url: /img
  static_dir: static/img

- url: /script
  static_dir: static/script

- url: /styles
  static_dir: static/styles